background_opacity 0.7

enable_audio_bell no

window_padding_width 10 20

draw_minimal_borders yes

placement_strategy center
cursor-shape beam
cursor_blink_interval 0

modify_font line_height 110%

include theme.conf

font_family family="JetBrainsMono Nerd Font"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0

include ~/.cache/wal/colors-kitty.conf
